//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobranzaReferenciadosMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza_Factura
    {
        public int id { get; set; }
        public string Cod_ramo { get; set; }
        public string RFC { get; set; }
        public int nro_pol { get; set; }
        public int ID_RUV { get; set; }
        public int ID_SII { get; set; }
        public string TipoPoliza { get; set; }
    }
}
