//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobranzaReferenciadosMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboPago
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Referencia1 { get; set; }
        public string Referencia2 { get; set; }
        public decimal Monto { get; set; }
        public string TipoMovimiento { get; set; }
        public string Banco { get; set; }
        public string Leyenda { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public bool Validado { get; set; }
        public string RFC { get; set; }
        public string CodRamoNroPol { get; set; }
    }
}
