//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobranzaReferenciadosMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referencia_Fovi
    {
        public int Id { get; set; }
        public int Id_asig { get; set; }
        public decimal Prima_neta { get; set; }
        public string No_Referencia { get; set; }
        public string Estatus_Pago { get; set; }
        public System.DateTime Date_Reg { get; set; }
        public string User_Reg { get; set; }
        public string User_Pago { get; set; }
        public Nullable<System.DateTime> fecha_Pago { get; set; }
    }
}
